packages:
  - desktop
  - apps/*
  - '!apps/*/playground'
  - packages/*
  - '!packages/*/playground'
  - themes/*
  - '!themes/*/playground'
  - plugins/*
  - '../../nuxt-desktop'

catalog:
  typescript: ~6.0.3

blockExoticSubdeps: false

allowBuilds:
  '@owdproject/*': true
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true
  audiobuffer-to-wav: true
  "audiobuffer-to-wav@https://codeload.github.com/torch2424/audiobuffer-to-wav/tar.gz/8878a20c5cc7e457b113dabfb1781ad4178f9c62": true
